name: Deploy on merge to main

on:
  pull_request:
    types: [closed]
    branches:
      - main

concurrency:
  group: deploy-main
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy over SSH and rebuild with docker compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            set -euo pipefail
            cd "/opt/tg-brainai"
            git fetch --all --prune
            git reset --hard origin/main
            docker compose pull || true
            docker compose up -d --build --remove-orphans
            docker image prune -f


